version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
        name: update npm
        command: 'sudo npm install -g npm@latest'
      - run:
        name: update dependency
        command: 'npm install'
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
        name: run code test
        command: 'npm test'
      - run:
        name: run code coverage
        command: './node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov report'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
        path: test-results.xml
